name: Dokka Deployment
on: 
  push:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Create DokkaHtml
        run: ./gradlew dokkaHtml
        
      - name: Print Current Folder
        run: pwd
        
      - name: Print ls
        run: ls -al

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages-html
          FOLDER: app/build/dokka/html/
